[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you can set these in Netlify UI instead)
# [context.production.environment]
#   VITE_API_URL = "https://44e793c2b2c9.ngrok-free.app"

# [context.deploy-preview.environment]
#   VITE_API_URL = "https://44e793c2b2c9.ngrok-free.app"

# [context.branch-deploy.environment]
#   VITE_API_URL = "https://44e793c2b2c9.ngrok-free.app"